In [1]:
import pandas as pd
import requests
from citipy import citipy
from config import weather_api_key
import gmaps
import gmaps.datasets
from config import g_key
from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt

In [2]:
gmaps.configure(api_key=g_key)

In [3]:
#import weather data from part 2 as new data frame
vacation_data_to_load=("weather_data/WeatherPy_vacation.csv")
vacation_data_df= pd.read_csv("weather_data/WeatherPy_vacation.csv")
vacation_data_df
.head(10)

,City ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Henties Bay,NaN,60.01,clear sky,-22.12,14.28,Fishermans Guest House
1,3,Ushuaia,AR,44.60,scattered clouds,-54.81,-68.31,Albatros Hotel
2,4,Mar Del Plata,AR,52.52,clear sky,-46.43,-67.52,Hotel Costanera Del Sur
3,5,Kruisfontein,ZA,59.31,overcast clouds,-34.00,24.73,Oyster Bay House Rental
4,11,Vaini,IN,67.87,few clouds,15.34,74.49,Dandeli Lake County
5,12,Castro,CL,66.20,broken clouds,-42.48,-73.76,Hotel Esmeralda
6,15,Ulladulla,AU,59.00,broken clouds,-35.36,150.48,Sandpiper Motel
7,16,Ewa Beach,US,77.00,broken clouds,21.32,-158.01,Parkside By Gentry
8,17,Bluff,AU,60.48,clear sky,-23.58,149.07,Bluff Hotel
9,18,Maldonado,UY,71.60,scattered clouds,-34.91,-54.96,Joan Miro Hotel

In [4]:
vacation_stop1 = vacation_data_df.loc[vacation_data_df["City"] == "Saint-Pierre"]
vacation_stop2 = vacation_data_df.loc[vacation_data_df["City"] == "Paris" ]
vacation_stop3 = vacation_data_df.loc[vacation_data_df["City"] == "Veraval"]
vacation_stop4 = vacation_data_df.loc[vacation_data_df["City"] == "Creil"]
vacation_stop_four=pd.concat([vacation_stop1, vacation_stop2,vacation_stop3,vacation_stop4], ignore_index=True)
vacation_stop_four_short=vacation_stop_four[['Lat','Lng']]
Lat_mean=vacation_stop_four_short['Lat'].mean()
Lng_mean=vacation_stop_four_short['Lng'].mean()
print('Mean Lattituede is', Lat_mean ,', and mean longitude is', Lng_mean)
vacation_stop_tuple = list(zip(*map(vacation_stop_four_short.get, vacation_stop_four_short)))
print(vacation_stop_tuple)
vacation_stop_four

Mean Lattituede is 49.18 , and mean longitude is 2.4425
[(48.95, 4.24), (48.86, 2.35), (49.65, 0.71), (49.26, 2.47)]

,City ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,172,Saint-Pierre,FR,41.00,few clouds,48.95,4.24,Auberge des Moissons
1,161,Paris,FR,44.01,overcast clouds,48.86,2.35,Citadines Les Halles Paris (Apart Hotel Paris)
2,381,Veraval,FR,44.60,moderate rain,49.65,0.71,Le Manoir aux Vaches
3,499,Creil,FR,44.01,broken clouds,49.26,2.47,Campanile

In [5]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [6]:
vacation_info = [info_box_template.format(**row) for index, row in vacation_stop_four.iterrows()]

In [27]:
Saint_Pierre= vacation_stop_tuple[0]
Paris= vacation_stop_tuple[1]
Veraval= vacation_stop_tuple[2]
Creil = vacation_stop_tuple[3]

fig2 = gmaps.figure(center=(Lat_mean, Lng_mean), zoom_level=8)
fig2.add_layer(gmaps.bicycling_layer()),
fig2.add_layer(gmaps.transit_layer()),
fig2.add_layer(gmaps.transit_layer()),
fig2.add_layer(gmaps.traffic_layer()),
locations = vacation_stop_four[["Lat", "Lng"]]
marker_layer = gmaps.marker_layer(locations)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info )
fig2.add_layer(marker_layer)
fig2
#create an vacation map.png
plt.savefig("weather_data/WeatherPy_travel_map.png")

In [28]:
Saint_Pierre= vacation_stop_tuple[0]
Paris= vacation_stop_tuple[1]
Veraval= vacation_stop_tuple[2]
Creil = vacation_stop_tuple[3]

fig = gmaps.figure()
Saint_Pierre2Veraval= gmaps.directions_layer( Saint_Pierre,Veraval, waypoints=[Creil, Paris])
fig.add_layer(Saint_Pierre2Veraval)
fig

#create an vacation map.png
plt.savefig("weather_data/WeatherPy_travel_map_markers.png")